stages:          # List of stages for jobs, and their order of execution
  - test
  - clear_cach
  - build
  - deploy

test:
  stage: test
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "done"

build:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

clear_cach:
  stage: clear_cach
  script:
    - cd /home/wepark/doer
    - docker-compose stop frontend
    - docker-compose rm -f frontend

deploy:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - cd /home/wepark/doer
    - sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=$CI_COMMIT_SHA/" .env
    - docker-compose up -d --build frontend
    - echo "Application successfully deployed."
  only:
    - main
