stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
  - clear_cach

test:
  stage: test
  script: 
    - cd /home/wepark/doer
    - ls
    - cd /home/wepark/doer/parklive-front
    - ls

build:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Start Build..."
    - cd /home/wepark/doer/parklive-front
    - sudo git pull
    - echo "Compile complete."

clear_cach:
  stage:
  script:
    - cd /home/wepark/doer
    - docker-compose stop frontend
    - docker-compose rm -f frontend

deploy:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - cd /home/wepark/doer
    - docker-compose up -d --build frontend
    - echo "Application successfully deployed."
