name: Deploy on main Update

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            # check repo
            - name: Checkout code
              uses: actions/checkout@v3

            # set up Docker
            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            # rm old front cont
            - name: Stop and remove old front container
              run: |
                  cd /home/wepark/doer
                  docker-compose stop frontend
                  docker-compose rm -f frontend

            # build/start new cont
            - name: Build and start updated front container
              run: |
                  cd /home/wepark/doer/team2-FE
                  sudo git pull origin main
                  cd ..
                  docker-compose up -d --build frontend
